### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2016-T13-C1/main#90]
## Developer guide
- **Architecture**
  - Are you planning to use the same architecture as AddressBook? If there are changes, pleas updated it to reflect the architecture of your product.
- **Sequence diagram**
  - Consider adding a sequence diagram for add/edit command since it gives a better idea how to write complex sequence diagrams
- **UI Component**
  - Good to see you have removed the `BrowserPanel` from the class diagram, reflecting the current design of the UI. :+1: 
  - I find the image little distorted (saved in smaller resolution and scaled up, may be?). Please try to fix it if possible.
- **Model component**
  - Please update the class diagram to reflect your project. While you are at it, please indicate the multiplicity of relevant classes in the diagram.
- **Storage component**
  - Are you sure about the notation in this diagram? (Please remind me to clarify during next tutorial!)
- **Testing**
  - Do you still use `UrlUtilTest`? If I remember right you don't use the browser panel, right?
- Suggested additions:
  - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
  - Similarly, you can explain other interesting design decisions you made.
## User guide
- Please change the screenshots to reflect your product
- `Floating task` may not mean much to the user. Try to come up with a more "user friendly" name.
- You can add more screenshots if possible; where applicable, consider using partial screenshots so that if you change something in other parts of the UI, you don't need to update all screenshots.
- Do you plan to support additional options to `add`/`edit` like tags, priority, reminder etc? If so, please include the details in the user guide.
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Comment by sunset1215** [comment]
@okkhoy 
Regarding giving examples for each command in 'Command Summary' section, there are examples given under the 'Features' section already. So should we move the examples from 'Features' section into 'Command Summary'? Or we should give another set of examples in 'Command Summary' section?

**Comment by okkhoy** [comment]
You can either copy-paste them or give new examples.
The idea is testers have 30 mins and they shouldn't spend time to find
examples.
